Shahenda
freska-cms/freska pull request #1
Opened 2018-01-22 10:48 UTC by shahendaeldeeb

Updating freska migrations.

2018-01-22 16:47 UTC, mcherri requested changes
Please fix minor issue

2018-01-22 16:47 UTC, mcherri commented on migrate.go
> +				}else {
Is this a bug in Fragmenta? Anyway the else is not well formatted.

2018-02-22 13:24 UTC, mcherri requested changes
A small question

2018-02-22 13:24 UTC, mcherri commented on migrate.go
> +				} else {
Why are we only breaking from this else?

2018-02-25 09:21 UTC, shahendaeldeeb commented on migrate.go
> +				} else {
As this is the only else inside loop of sql files

2018-02-25 09:58 UTC, mcherri commented on migrate.go
> +				} else {
We are testing for `err == nil`, which will never happen. If this is not true then we need to talk.

2018-02-27 12:59 UTC, mcherri requested changes
A minor change.

2018-02-27 12:59 UTC, mcherri commented on migrate.go
> +				log.Printf("ERROR loading sql migration:%s\n", err)
I think this line only belongs to the else because `err` can be `nil` sometimes.

2018-02-28 13:30 UTC, mcherri approved these changes
:100:

2018-02-28 13:31 UTC, merged